version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn package
  post_build:
    commands:
    - echo "Entered post build phase"
    - mv target/bluegreendeploymentdemo-v1.war bluegreendeploymentdemo-v2.war
artifacts:
  files:
    - bluegreendeploymentdemo-v2.war